import {browserConfig} from './browser-config.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const {baseUrl,launchOptions}=browserConfig();const browser=await chromium.launch(launchOptions);const checks=[];
try{for(const [name,width,reduced,blocked] of [['desktop',1440,false,false],['phone',390,true,false],['narrow-storage',320,false,true]]){
 const ctx=await browser.newContext({viewport:{width,height:900},reducedMotion:reduced?'reduce':'no-preference'});if(blocked)await ctx.addInitScript(()=>Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError');});const p=await ctx.newPage();p.setDefaultTimeout(8000);await p.goto(baseUrl+'/start/');
 await p.locator('[data-step=direction]').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#step-direction').isVisible(),true);
 await p.locator('[data-brief-feel=playful]').click();await p.locator('[data-step=goal]').click();await p.locator('#goal').fill('A useful website');await p.locator('#audience').fill('People browsing by phone');await p.locator('#desiredAction').fill('Read the work');
 await p.locator('[data-step=scope]').click();await p.locator('#budget').fill('Discuss after scope');await p.locator('#referenceURLs').fill('javascript:alert(1)');await p.locator('[data-step=review]').click();assert.equal(await p.locator('#brief-errors').isVisible(),true);assert.equal(await p.evaluate(()=>document.activeElement.id),'brief-errors');await p.locator('#brief-errors a').first().click();assert.equal(await p.evaluate(()=>document.activeElement.id),'referenceURLs');await p.locator('#referenceURLs').fill('https://example.com/work');
 await p.locator('[data-step=review]').click();assert.equal(await p.locator('#step-review').isVisible(),true);assert.match(await p.locator('#brief-review').textContent(),/A useful website/);assert.match(await p.locator('#brief-review').textContent(),/Playful/);assert.match(await p.locator('#step-review').textContent(),/pending owner approval/i);
 await p.locator('[data-step=goal]').click();assert.equal(await p.locator('#goal').inputValue(),'A useful website');await p.locator('[data-step=review]').click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(blocked)assert.match(await p.locator('#draft-status').textContent(),/Temporary/);else{await p.goto(baseUrl);assert.equal(await p.locator('button[data-feel=playful]').getAttribute('aria-pressed'),'true');await p.locator('button[data-feel=cinematic]').click();await p.goBack();assert.equal(await p.locator('#goal').inputValue(),'A useful website');assert.equal(await p.locator('#saved-direction').textContent(),'Cinematic');await p.locator('[data-step=review]').click();}
 await p.screenshot({path:`evidence/brief-${name}.png`,fullPage:true});checks.push({name,width,reduced,blocked,checks:['keyboard steps','edit/back retention','URL error summary/focus','review derived from draft','approval labels','no overflow',blocked?'temporary storage usable':'home direction continuity']});await ctx.close();
 }
 const ctx=await browser.newContext();const p=await ctx.newPage();p.setDefaultTimeout(8000);await p.goto(baseUrl+'/start/');await p.locator('[data-step=review]').click();assert.match(await p.locator('#brief-errors').textContent(),/goal/i);await p.locator('#brief-errors a').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'goal');await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('opening-brief-v1'));d.goal='Updated after navigation';d.feel='cinematic';d.revision++;localStorage.setItem('opening-brief-v1',JSON.stringify(d));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});assert.equal(await p.locator('#goal').inputValue(),'Updated after navigation');assert.equal(await p.locator('#saved-direction').textContent(),'Cinematic');await ctx.close();checks.push({name:'empty-goal',checks:['review requires goal; error link focuses field']});
 await writeFile('evidence/brief-browser.json',JSON.stringify({runAt:new Date().toISOString(),browser:browser.version(),checks},null,2));console.log('PASS: four-step brief desktop/phone/reduced/storage/error journeys.');}finally{await browser.close();}
