import {browserConfig} from './browser-config.mjs';
const {baseUrl,launchOptions}=browserConfig();
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch(launchOptions);
const base=baseUrl;const results=[];
async function profile(name,options={},setup){const context=await browser.newContext(options);if(setup)await setup(context);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForLoadState('networkidle');return {context,page,errors,name};}
async function noOverflow(page){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
async function metrics(page){return page.evaluate(()=>{const h=document.querySelector('#renderer');const frames=JSON.parse(h?.dataset.frames||'[]').sort((a,b)=>a-b);return {renderer:h?{...h.dataset}:null,activeP95:frames[Math.ceil(frames.length*.95)-1]??null,resources:performance.getEntriesByType('resource').map(e=>({name:new URL(e.name).pathname,encoded:e.encodedBodySize,decoded:e.decodedBodySize,transfer:e.transferSize,duration:e.duration})),navigation:performance.getEntriesByType('navigation').map(e=>({encoded:e.encodedBodySize,decoded:e.decodedBodySize,transfer:e.transferSize,domContentLoaded:e.domContentLoadedEventEnd})),lcp:window.__lcp??null};});}
// Record actual LCP entry and whether the native transition API supplied a transition.
async function instrument(context){await context.addInitScript(()=>{new PerformanceObserver(list=>{window.__lcp=list.getEntries().at(-1)?.startTime;}).observe({type:'largest-contentful-paint',buffered:true});addEventListener('pageswap',e=>sessionStorage.setItem('observed-vt',String(!!e.viewTransition)));});}
const d=await profile('desktop-full',{viewport:{width:1440,height:1000},deviceScaleFactor:1},instrument);const p=d.page;
await p.waitForSelector('#renderer[data-ready=true]');await noOverflow(p);await p.screenshot({path:'evidence/desktop-full.png',fullPage:true});await p.screenshot({path:'evidence/desktop-hero.png'});
await p.locator('button[data-feel=playful]').click();assert.equal(await p.locator('button[data-feel=playful]').getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('opening-brief-v1')).feel),'playful');
for(const feel of ['cinematic','precise','playful','precise','cinematic']){await p.locator(`button[data-feel=${feel}]`).click();await p.waitForTimeout(100);}
await p.waitForTimeout(850);assert.equal(await p.locator('#renderer').getAttribute('data-angles'),'[-38,42,18]');const count=await p.locator('#renderer').getAttribute('data-choreographies');await p.locator('button[data-feel=cinematic]').click();assert.equal(await p.locator('#renderer').getAttribute('data-choreographies'),count);
results.push({name:d.name,checks:['immediate choice + draft revision','five rapid retargets','repeat no replay','no overflow'],metrics:await metrics(p)});
await p.locator('button[data-feel=playful]').click();await p.evaluate(()=>scrollTo(0,400));await p.waitForTimeout(100);assert.equal(await p.locator('#stage').getAttribute('data-bridge'),'true');await p.screenshot({path:'evidence/scroll-handoff.png'});await p.locator('#mode-toggle').evaluate(b=>{if(b instanceof HTMLElement)b.click();});await p.waitForTimeout(100);assert.equal(await p.locator('#stage').getAttribute('data-bridge'),'false');assert.equal(await p.locator('#poster-image').evaluate(i=>getComputedStyle(i.parentElement).visibility),'visible');await p.locator('#mode-toggle').evaluate(b=>{if(b instanceof HTMLElement)b.click();});await p.evaluate(()=>scrollTo(0,1800));await p.waitForTimeout(100);await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(150);assert.equal(await p.locator('#renderer').getAttribute('data-angles'),'[-28,34,14]');assert.equal(await p.locator('#stage').getAttribute('data-bridge'),'false');
// Stage-image → case-image native route continuity and Back.
await p.locator('.stage-proof').click();await p.waitForURL('**/work/opening-study/');await p.screenshot({path:'evidence/transition-mid.png'});await p.waitForTimeout(650);assert.equal(await p.locator('#route-heading').count(),1);assert.equal(await p.evaluate(()=>document.activeElement.id),'route-heading');await p.screenshot({path:'evidence/case-desktop.png',fullPage:true});assert.equal(await p.evaluate(()=>sessionStorage.getItem('observed-vt')),'true');await p.goBack();await p.waitForSelector('button[data-feel=playful][aria-pressed=true]');await p.waitForTimeout(300);
// Ordinary modified link opens a new tab.
const popupPromise=d.context.waitForEvent('page');await p.locator('.stage-proof').click({modifiers:['Control']});const popup=await popupPromise;await popup.waitForLoadState();assert.ok(popup.url().endsWith('/work/opening-study/'));await popup.close();
await p.locator('.project-image').scrollIntoViewIfNeeded();const workY=await p.evaluate(()=>scrollY);await p.locator('.project-image').click();await p.waitForURL('**/work/opening-study/');await p.waitForTimeout(650);await p.goBack();await p.waitForSelector('.project-image');await p.waitForTimeout(300);assert.ok(Math.abs(await p.evaluate(()=>scrollY)-workY)<2,'Back restores source scroll');await p.locator('.project-image').click();await p.waitForURL('**/work/opening-study/');await p.waitForTimeout(650);await p.locator('nav a[href="/start/"]').click();await p.waitForURL('**/start/');assert.equal(await p.locator('#saved-direction').textContent(),'Playful');
await p.locator('#goal').fill('An accessible interactive portfolio');await p.locator('[data-step=review]').click();const downloadPromise=p.waitForEvent('download');await p.locator('#export-draft').click();const download=await downloadPromise;await download.saveAs('evidence/direction-export.json');await p.goBack();await p.waitForURL('**/work/opening-study/');await p.goto(base+'/work/opening-study/');assert.equal(await p.locator('.case-facts').count(),1);
// Cancel an in-flight navigation with a newer native navigation.
await p.goto(base);await p.waitForSelector('.stage-proof');await p.locator('.stage-proof').click();await p.goto(base+'/start/');assert.ok(p.url().endsWith('/start/'));assert.equal(await p.locator('#route-heading').textContent(),'Make roomfor an idea.');
results.push({name:'native-navigation',checks:['stage image transition API observed','case direct URL','Back + selected state + work source scroll','work image route','modified click','new navigation cancellation','direction note export'],errors:d.errors});
await d.context.close();
for(const width of [390,320]){const m=await profile(`phone-${width}`,{viewport:{width,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true},instrument);await noOverflow(m.page);await m.page.screenshot({path:`evidence/phone-${width}-hero.png`});assert.ok(await m.page.locator('.hero-actions').isVisible());await m.page.locator('button[data-feel=cinematic]').scrollIntoViewIfNeeded();await m.page.waitForSelector('#renderer[data-ready=true]');await m.page.locator('button[data-feel=cinematic]').click();await m.page.waitForTimeout(850);assert.equal(await m.page.locator('#renderer').getAttribute('data-angles'),'[-38,42,18]');assert.ok(Number(await m.page.locator('#renderer').getAttribute('data-frame-count'))>20,'phone selection must actually animate');await m.page.screenshot({path:`evidence/phone-${width}-stage.png`});await noOverflow(m.page);await m.page.screenshot({path:`evidence/phone-${width}.png`,fullPage:true});results.push({name:m.name,checks:['text then stage order','touch selection','no horizontal overflow','DPR capped to 1'],metrics:await metrics(m.page),errors:m.errors});await m.context.close();}
for(const mode of ['light','reduced','no-webgl','scene-load-failure']){const f=await profile(mode,{viewport:{width:390,height:844},reducedMotion:mode==='reduced'?'reduce':'no-preference'},async ctx=>{await instrument(ctx);if(mode==='light')await ctx.addInitScript(()=>localStorage.setItem('opening-mode','light'));if(mode==='no-webgl')await ctx.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.includes('webgl'))return null;return original.call(this,type,...args);};});if(mode==='scene-load-failure')await ctx.route('**/*renderer*.js',route=>route.abort());});await f.page.locator('button[data-feel=playful]').scrollIntoViewIfNeeded();await f.page.locator('button[data-feel=playful]').click();await f.page.waitForTimeout(700);assert.equal(await f.page.locator('button[data-feel=playful]').getAttribute('aria-pressed'),'true');assert.equal(await f.page.locator('canvas').count(),0);await noOverflow(f.page);await f.page.screenshot({path:`evidence/${mode}.png`,fullPage:true});const costs=await metrics(f.page);if(mode==='light'||mode==='reduced')assert.equal(costs.resources.some(r=>r.name.includes('renderer')),false);await f.page.locator('.stage-proof').click();await f.page.waitForURL('**/work/opening-study/');results.push({name:mode,checks:['authored still','selected state','case link','no canvas',...(['light','reduced'].includes(mode)?['zero renderer runtime requests']:[])],metrics:costs,errors:f.errors});await f.context.close();}
const lost=await profile('context-loss',{viewport:{width:1440,height:1000}});await lost.page.waitForSelector('canvas');await lost.page.locator('canvas').evaluate(c=>c.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await lost.page.waitForTimeout(200);assert.equal(await lost.page.locator('canvas').count(),0);await lost.page.locator('button[data-feel=playful]').click();assert.equal(await lost.page.locator('button[data-feel=playful]').getAttribute('aria-pressed'),'true');await lost.page.screenshot({path:'evidence/context-loss.png'});await lost.page.goto(base+'/work/opening-study/');await lost.page.goto(base);await lost.page.waitForTimeout(300);assert.equal(await lost.page.locator('canvas').count(),0);results.push({name:'context-loss',checks:['poster immediately restored','choice retained','terminal degradation survives routes'],errors:lost.errors});await lost.context.close();
// JS-disabled useful route and proof.
const plain=await profile('no-javascript',{javaScriptEnabled:false,viewport:{width:390,height:844}});await noOverflow(plain.page);await plain.page.locator('.stage-proof').click();await plain.page.waitForURL('**/work/opening-study/');assert.ok(await plain.page.locator('.case-image img').isVisible());results.push({name:'no-javascript',checks:['HTML hero + proof','ordinary case link','case direct content']});await plain.context.close();

// Cold-session home + native scroll costs, separated from requested selection posters.
for(const mode of ['full','light','reduced']){const cold=await profile(`cold-${mode}`,{viewport:{width:1440,height:1000},reducedMotion:mode==='reduced'?'reduce':'no-preference'},async ctx=>{await instrument(ctx);if(mode==='light')await ctx.addInitScript(()=>localStorage.setItem('opening-mode','light'));});const firstView=await metrics(cold.page);await cold.page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await cold.page.waitForLoadState('networkidle');const journey=await metrics(cold.page);results.push({name:`cold-${mode}`,firstView,metrics:journey,errors:cold.errors});await cold.context.close();}

await writeFile('evidence/browser-results.json',JSON.stringify({runAt:new Date().toISOString(),browser:browser.version(),environment:'Linux Chromium headless, SwiftShader software WebGL; localhost preview, no throttling. Phone is viewport/touch emulation, not hardware.',results},null,2));await browser.close();console.log(`PASS: ${results.length} browser scenarios. See evidence/browser-results.json.`);
