import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';import {browserConfig} from './browser-config.mjs';
const {baseUrl,launchOptions}=browserConfig();const out=process.env.OPENING_MOTION_EVIDENCE||'evidence/motion';await mkdir(out,{recursive:true});
const browser=await chromium.launch(launchOptions),results=[];
async function instrument(context){await context.addInitScript(()=>{window.__motionTrace=[];new MutationObserver(()=>{const h=document.querySelector('#renderer');if(h?.dataset.ready==='true'&&h.dataset.angles&&window.__motionTrace.length<500)window.__motionTrace.push({at:performance.now(),angles:h.dataset.angles,active:h.dataset.active,frames:h.dataset.frameCount});}).observe(document,{subtree:true,attributes:true,attributeFilter:['data-angles']});});}
try{
 const slow=await browser.newContext({viewport:{width:1440,height:1000}});await instrument(slow);await slow.addInitScript(()=>{const raf=requestAnimationFrame.bind(window);let delayed=false;window.requestAnimationFrame=callback=>raf(time=>{if(!delayed){delayed=true;setTimeout(()=>callback(performance.now()),1500);}else callback(time);});});const slowPage=await slow.newPage();await slowPage.goto(baseUrl);await slowPage.waitForSelector('#renderer[data-ready=true]');await slowPage.waitForFunction(()=>new Set(window.__motionTrace.map(x=>x.angles)).size>=3,{},{timeout:3500});await slowPage.waitForFunction(()=>document.querySelector('#renderer')?.dataset.active==='false');results.push({name:'delayed-first-frame',checks:['1.5second first-frame scheduling delay does not consume entrance']});await slow.close();
 for(const width of [1440,390]){
  const ctx=await browser.newContext({viewport:{width,height:width===1440?1000:844},recordVideo:{dir:out,size:{width:width===1440?960:390,height:width===1440?667:844}}});await instrument(ctx);const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.goto(baseUrl);await p.locator('#stage').scrollIntoViewIfNeeded();await p.waitForSelector('#renderer[data-ready=true]');
  await p.waitForFunction(()=>new Set(window.__motionTrace.map(x=>x.angles)).size>=3,{},{timeout:3500});
  await p.waitForFunction(()=>document.querySelector('#renderer')?.dataset.active==='false');
  assert.equal(await p.locator('#renderer').getAttribute('data-angles'),'[-18,22,8]');
  const entryTrace=await p.evaluate(()=>window.__motionTrace);assert.equal(entryTrace[0].angles,'[-18,22,8]','first rendered frame matches selected poster pose');assert.ok(entryTrace.some(x=>x.active==='true'),'entry actually animates');
  const idleFrames=await p.locator('#renderer').getAttribute('data-frame-count');await p.waitForTimeout(180);assert.equal(await p.locator('#renderer').getAttribute('data-frame-count'),idleFrames);
  for(const feel of ['playful','cinematic','precise','playful']){await p.locator(`button[data-feel=${feel}]`).click();assert.equal(await p.locator(`button[data-feel=${feel}]`).getAttribute('aria-pressed'),'true');await p.waitForTimeout(90);}
  await p.waitForFunction(()=>document.querySelector('#renderer')?.dataset.active==='false');
  assert.equal(await p.locator('#renderer').getAttribute('data-angles'),'[-28,34,14]');
  const repeated=await p.locator('#renderer').getAttribute('data-choreographies');await p.locator('button[data-feel=playful]').click();assert.equal(await p.locator('#renderer').getAttribute('data-choreographies'),repeated);
  await p.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await p.waitForTimeout(80);await p.locator('#stage').scrollIntoViewIfNeeded();await p.waitForTimeout(160);assert.equal(await p.locator('#renderer').getAttribute('data-active'),'false');
  await p.locator('#mode-toggle').click();await p.locator('#mode-toggle').click();await p.waitForSelector('#renderer[data-ready=true]');assert.equal(await p.locator('#renderer').getAttribute('data-active'),'false','Full toggle must not replay entry');
  await p.locator('.stage-proof').click();await p.waitForURL('**/work/staypilot/');await p.goBack();await p.waitForSelector('#renderer[data-ready=true]');assert.equal(await p.locator('#renderer').getAttribute('data-active'),'false','Back must resume selected pose without entrance replay');
  assert.match(await p.locator('#motion-hint').textContent(),/another feel/);
  assert.deepEqual(errors,[]);await p.screenshot({path:`${out}/full-${width}.png`});
  const video=p.video();await ctx.close();await video.saveAs(`${out}/full-${width}.webm`);await video.delete();
  results.push({width,checks:['cold Full visibly opens without a feel click','idle RAF stops','rapid selection immediate and interruptible','repeat no replay','scroll reentry and Full toggle do not replay entry'],entryTrace,errors});
 }
 const delayed=await browser.newContext({viewport:{width:1440,height:1000}});await instrument(delayed);await delayed.route('**/renderer.*.js',async route=>{await new Promise(r=>setTimeout(r,800));await route.continue();});const p=await delayed.newPage();await p.goto(baseUrl);await p.locator('button[data-feel=cinematic]').click();assert.equal(await p.locator('button[data-feel=cinematic]').getAttribute('aria-pressed'),'true');await p.waitForSelector('#renderer[data-ready=true]');await p.waitForFunction(()=>new Set(window.__motionTrace.map(x=>x.angles)).size>=3,{},{timeout:3500});await p.waitForFunction(()=>document.querySelector('#renderer')?.dataset.active==='false');assert.equal(await p.locator('#renderer').getAttribute('data-angles'),'[-38,42,18]');results.push({name:'delayed-module',checks:['selection before renderer resolves stays immediate','opening uses latest chosen feel']});await delayed.close();
 const storage=await browser.newContext({viewport:{width:390,height:844}});await storage.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Storage unavailable','QuotaExceededError');};});const sp=await storage.newPage();await sp.goto(baseUrl);await sp.locator('button[data-feel=cinematic]').click();assert.equal(await sp.locator('button[data-feel=cinematic]').getAttribute('aria-pressed'),'true');assert.match(await sp.locator('#direction-status').textContent(),/Temporary/);assert.match(await sp.locator('#motion-hint').textContent(),/updates immediately/);results.push({name:'storage-unavailable',checks:['selection remains immediate','visible hint makes no persistence promise']});await storage.close();
 for(const mode of ['light','reduced','failure']){
  const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:mode==='reduced'?'reduce':'no-preference'});
  if(mode==='light')await ctx.addInitScript(()=>localStorage.setItem('opening-mode','light'));
  if(mode==='failure')await ctx.addInitScript(()=>sessionStorage.setItem('opening-render-failure','Test retained failure'));
  const p=await ctx.newPage();await p.goto(baseUrl);await p.locator('button[data-feel=cinematic]').click();assert.equal(await p.locator('button[data-feel=cinematic]').getAttribute('aria-pressed'),'true');await p.waitForTimeout(180);assert.equal(await p.locator('canvas').count(),0);assert.match(await p.locator('#motion-hint').textContent(),mode==='reduced'?/reduced motion/i:mode==='light'?/Full mode/:/unavailable/i);results.push({mode,checks:['authored still and immediate selected state','visible explanation for no spatial motion']});await ctx.close();
 }
 await writeFile(`${out}/results.json`,JSON.stringify({runAt:new Date().toISOString(),baseUrl,browser:browser.version(),results,limits:'Chrome/SwiftShader with phone emulation. WebM records actual normal renderer frames without timing edits; software recording is not physical performance calibration.'},null,2));console.log('PASS: first Full opening, delayed latest selection, retarget/repeat/reentry and explained alternatives.');
}finally{await browser.close();}
