import {chromium} from 'playwright';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});const output=[];
for(const [name,width,height,dpr] of [['desktop',1440,1000,1.5],['phone',390,844,3]]){
 const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,isMobile:name==='phone',hasTouch:name==='phone'});const page=await context.newPage();await page.goto('http://localhost:4322/');if(name==='phone')await page.locator('.feel-controls').scrollIntoViewIfNeeded();await page.waitForSelector('#renderer[data-ready=true]');
 const before=await page.locator('#renderer').getAttribute('data-choreographies');await page.locator('button[data-feel=playful]').focus();await page.keyboard.press('Enter');await page.waitForTimeout(750);assert.notEqual(await page.locator('#renderer').getAttribute('data-choreographies'),before);await page.screenshot({path:`evidence/${name}-keyboard.png`});
 for(const feel of ['cinematic','precise','playful','cinematic']){await page.locator(`button[data-feel=${feel}]`).click();await page.waitForTimeout(850);}
 const stats=await page.locator('#renderer').evaluate(h=>({...h.dataset}));const times=JSON.parse(stats.frames).sort((a,b)=>a-b);output.push({name,viewport:{width,height},emulatedDpr:dpr,p95:times[Math.ceil(times.length*.95)-1],samples:times.length,stats});
 if(name==='desktop'){await page.locator('button[data-feel=precise]').click();await page.waitForTimeout(650);await page.locator('#stage').screenshot({path:'evidence/render-match.png'});await page.locator('#mode-toggle').click();await page.waitForTimeout(150);await page.locator('#stage').screenshot({path:'evidence/poster-match.png'});}
 // Storage unavailable still commits selection and exports a session note.
 await context.close();
}
const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('unavailable','QuotaExceededError');};});const page=await context.newPage();await page.goto('http://localhost:4322/');await page.locator('button[data-feel=playful]').click();assert.equal(await page.locator('button[data-feel=playful]').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#direction-status').textContent(),/Temporary/);await page.goto('http://localhost:4322/start/');await page.locator('#goal').fill('A temporary note');assert.match(await page.locator('#draft-status').textContent(),/Temporary/);await context.close();
const sheet=await browser.newPage({viewport:{width:1800,height:650},deviceScaleFactor:1});await sheet.goto('http://localhost:4322/');await sheet.setContent(`<html><body style="margin:0;background:#171a1c;color:#f4f1ea;font:14px Arial"><div style="padding:28px 35px;display:flex;justify-content:space-between"><b>THE OPENING / ORIGINAL POSE SHEET</b><span>Three sibling pivots · +Y / +Y / +X · owner review pending</span></div><div style="display:flex">${[['precise','−18 / 22 / 8','540'],['playful','−28 / 34 / 14','660'],['cinematic','−38 / 42 / 18','760']].map(([f,a,t])=>`<div style="width:600px"><img src="http://localhost:4322/art/poster-${f}.png" width="600" height="500"/><p style="margin:15px 35px;display:flex;justify-content:space-between;text-transform:uppercase"><b>${f}</b><span>${a} deg · ${t} ms</span></p></div>`).join('')}</div></body></html>`);await sheet.waitForLoadState('networkidle');await sheet.screenshot({path:'evidence/pose-sheet.png'});
await writeFile('evidence/visual-audit.json',JSON.stringify({runAt:new Date().toISOString(),environment:'Headless Chromium + SwiftShader software rasterizer, sequential profile runs on shared Linux workspace; active RAF intervals, not physical-device or GPU timestamp measurements.',profiles:output,additionalChecks:['keyboard Enter selects and animates','focus capture','storage unavailable selection and note','matched poster/render screenshots','original pose sheet']},null,2));await browser.close();console.log('PASS: visual, keyboard, storage and sequential active traces.');
