import type {BriefDraftV1} from './types';
import {normalizeBrief} from './persistence';import {services,projects,referenceLabel} from './catalog';
export function snapshotDraft(draft:BriefDraftV1):Readonly<BriefDraftV1>{const normalized=normalizeBrief(draft);if(!normalized)throw new Error('Invalid anonymous brief.');const snapshot=normalized.draft;Object.freeze(snapshot.serviceIds);Object.freeze(snapshot.projectReferenceIds);Object.freeze(snapshot.referenceURLs);return Object.freeze(snapshot);}
function canonical(snapshot:Readonly<BriefDraftV1>){const normalized=normalizeBrief(snapshot);if(!normalized)throw new Error('Invalid anonymous brief snapshot.');return normalized.draft;}
export function serializeDraftJson(snapshot:Readonly<BriefDraftV1>):string{const d=canonical(snapshot);return JSON.stringify({...d,referenceAvailability:{services:services.filter(s=>d.serviceIds.includes(s.id)),projects:projects.filter(p=>d.projectReferenceIds.includes(p.id)),notice:'Unavailable references are omitted. Offers remain pending owner approval. Repository projects are owner-selected; contribution credits remain pending. The form study is a development placeholder.'}},null,2);}
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderPrintableHtml(snapshot:Readonly<BriefDraftV1>):string{
 const d=canonical(snapshot);
 const rows=[['Goal',d.goal],['Audience',d.audience],['Desired action',d.desiredAction],['Direction',d.feel[0]!.toUpperCase()+d.feel.slice(1)],['Scope',services.filter(s=>d.serviceIds.includes(s.id)).map(s=>s.label+' — pending owner approval').join('\n')],['Project references',projects.filter(p=>d.projectReferenceIds.includes(p.id)).map(referenceLabel).join('\n')],['Constraints',d.constraints],['Budget context',d.budget],['Timing',d.timing],['Reference URLs',(d.referenceURLs??[]).join('\n')]];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>The Opening — Brief revision ${d.revision}</title><style>body{font:16px/1.65 Arial,Helvetica,sans-serif;color:#171a1c;background:#fff;max-width:850px;margin:0 auto;padding:40px}h1{font-size:40px;line-height:1.15;letter-spacing:-1px}h2{font-size:22px}header{border-bottom:3px solid #ff5b3d;padding-bottom:20px}dl{display:grid;grid-template-columns:170px minmax(0,1fr);gap:0}dt,dd{padding:14px 0;margin:0;border-bottom:1px solid #ddd;white-space:pre-wrap;overflow-wrap:anywhere;break-inside:avoid}dt{font-weight:bold}footer{margin-top:35px;font-size:13px;color:#4d5551}small{font-size:13px}@media(max-width:600px){body{padding:20px}dl{grid-template-columns:1fr}dt{border:0;padding-bottom:0}dd{padding-top:5px}}@page{margin:18mm;size:A4}@media print{body{padding:0;max-width:none}h1,h2{break-after:avoid}header,footer{break-inside:avoid}}</style></head><body><main><header><p>THE OPENING / ANONYMOUS PROJECT BRIEF</p><h1>A starting point to keep.</h1><p>Revision ${d.revision} · ${escape(d.updatedAt)}</p><small>Draft ID: ${escape(d.draftId)}</small></header><section aria-labelledby="brief-heading"><h2 id="brief-heading">Your brief</h2><dl>${rows.map(([label,value])=>`<dt>${escape(label!)}</dt><dd>${escape(value||'Not specified')}</dd>`).join('')}</dl></section><footer><p>This is an anonymous brief export, not a submitted enquiry, booking or agreement. Contact delivery is not configured.</p><p>Unavailable references are omitted. Listed offers are pending owner approval. Repository projects are owner-selected, with contribution credits pending; the form study remains a development placeholder. Prototype data is not a client result.</p><p>This file works offline. Use your browser’s Print command to print or save it. No name, email or contact message fields are included.</p></footer></main></body></html>`;
}
