import {readDraftState,persistDraft,isFeel} from './draft';
import {reduceDraft} from './reducer';import {services,projects} from './catalog';import type {DraftAction,TextField} from './types';
const restored=readDraftState();let draft=restored.draft,saved=restored.storageStatus==='saved';
const steps=['goal','direction','scope','review'] as const;type Step=typeof steps[number];let step:Step='goal';
const form=document.querySelector<HTMLFormElement>('#brief-form')!,status=document.querySelector<HTMLElement>('#draft-status')!,summary=document.querySelector<HTMLElement>('#brief-errors')!;
const errors=new Map<string,string>();const fields=[...form.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('[data-brief-field]')];const urls=form.querySelector<HTMLTextAreaElement>('#referenceURLs')!;
const fieldStep=(id:string):Step=>['goal','audience','desiredAction'].includes(id)?'goal':'scope';
function renderErrors(){summary.replaceChildren();summary.hidden=errors.size===0;for(const el of [...fields,urls])el.setAttribute('aria-invalid',String(errors.has(el.id)));if(!errors.size)return;const title=document.createElement('p');title.textContent='Please check these fields before review:';summary.append(title);const list=document.createElement('ul');for(const [id,message] of errors){const li=document.createElement('li'),a=document.createElement('a');a.href='#'+id;a.textContent=message;li.append(a);list.append(li);}summary.append(list);}
function paint(){
 document.querySelector('#saved-direction')!.textContent=draft.feel[0]!.toUpperCase()+draft.feel.slice(1);
 form.querySelectorAll<HTMLButtonElement>('[data-brief-feel]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.briefFeel===draft.feel)));
 status.textContent=saved?`Anonymous brief saved on this device · revision ${draft.revision}.`:'Temporary brief — device storage is unavailable or recovery has not been saved. Export to keep it.';
 const review=document.querySelector('#brief-review')!;review.replaceChildren();const dl=document.createElement('dl');
 const rows=[['Goal',draft.goal],['Audience',draft.audience],['Desired action',draft.desiredAction],['Direction',draft.feel[0]!.toUpperCase()+draft.feel.slice(1)],['Scope',services.filter(s=>draft.serviceIds.includes(s.id)).map(s=>s.label+' (pending approval)').join(', ')],['Project references',projects.filter(p=>draft.projectReferenceIds.includes(p.id)).map(p=>p.label+' (development placeholder)').join(', ')],['Constraints',draft.constraints],['Budget context',draft.budget],['Timing',draft.timing],['Reference URLs',(draft.referenceURLs??[]).join('\n')],['Revision',String(draft.revision)]];
 for(const [label,value] of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label!;dd.textContent=value||'Not specified';dl.append(dt,dd);}review.append(dl);renderErrors();
}
function edit(action:DraftAction,id:string){try{draft=reduceDraft(draft,action);saved=persistDraft(draft);errors.delete(id);}catch{errors.set(id,id==='referenceURLs'?'Reference links must be up to eight HTTP(S) URLs without embedded credentials.':'This field exceeds its allowed length or has an invalid value.');}paint();}
function show(next:Step,focus=true){if(next==='review'){if(!draft.goal.trim())errors.set('goal','Add a goal before reviewing your brief.');else errors.delete('goal');if(errors.size){renderErrors();summary.focus();return;}}
 step=next;form.querySelectorAll<HTMLElement>('[data-brief-step]').forEach(el=>el.hidden=el.dataset.briefStep!==step);form.querySelectorAll<HTMLButtonElement>('[data-step]').forEach(b=>{if(b.dataset.step===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});document.querySelector<HTMLButtonElement>('#brief-back')!.disabled=step==='goal';document.querySelector<HTMLElement>('#brief-next')!.hidden=step==='review';if(focus)form.querySelector<HTMLElement>(`#step-${step} legend`)!.focus();}
for(const el of fields){el.value=draft[el.dataset.briefField as TextField]??'';el.addEventListener('input',()=>edit({type:'text',field:el.dataset.briefField as TextField,value:el.value},el.id));}
urls.value=(draft.referenceURLs??[]).join('\n');urls.addEventListener('input',()=>edit({type:'references',value:urls.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)},urls.id));
form.querySelectorAll<HTMLInputElement>('[data-id-field]').forEach(el=>{const field=el.dataset.idField as 'serviceIds'|'projectReferenceIds';el.checked=draft[field].includes(el.value);el.addEventListener('change',()=>edit({type:'ids',field,value:[...form.querySelectorAll<HTMLInputElement>(`[data-id-field=${field}]:checked`)].map(input=>input.value)},field));});
form.querySelectorAll<HTMLButtonElement>('[data-brief-feel]').forEach(b=>b.addEventListener('click',()=>{if(isFeel(b.dataset.briefFeel))edit({type:'feel',value:b.dataset.briefFeel},'feel');}));
form.querySelectorAll<HTMLButtonElement>('[data-step]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.step as Step)));
summary.addEventListener('click',e=>{const a=(e.target as HTMLElement).closest('a');if(!a)return;e.preventDefault();const id=a.hash.slice(1);show(fieldStep(id),false);document.getElementById(id)?.focus();});
form.addEventListener('submit',e=>{e.preventDefault();show(steps[Math.min(steps.indexOf(step)+1,3)]!);});document.querySelector('#brief-back')!.addEventListener('click',()=>show(steps[Math.max(steps.indexOf(step)-1,0)]!));
document.querySelector('#export-draft')!.addEventListener('click',()=>{const snapshot={...draft};const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`opening-brief-r${snapshot.revision}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=`Exported brief revision ${snapshot.revision}. This is not a submitted enquiry.`;});
document.querySelector('#draft-notices')!.textContent=restored.notices.join(' ');paint();show('goal',false);

addEventListener('pageshow',event=>{if(!event.persisted)return;const current=readDraftState();if(current.storageStatus==='temporary'){saved=false;paint();return;}if(saved&&current.draft.draftId===draft.draftId&&current.draft.revision>draft.revision){draft=current.draft;for(const el of fields)el.value=draft[el.dataset.briefField as TextField]??'';urls.value=(draft.referenceURLs??[]).join('\n');form.querySelectorAll<HTMLInputElement>('[data-id-field]').forEach(el=>el.checked=draft[el.dataset.idField as 'serviceIds'|'projectReferenceIds'].includes(el.value));errors.clear();document.querySelector('#draft-notices')!.textContent=current.notices.join(' ');paint();}});
